<a href="https://colab.research.google.com/github/vibhutidabas/Learning/blob/main/NLP/restaurant_review_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
data = pd.read_csv("/content/drive/MyDrive/Udemy learning path/NLP 8 projects/Restaurant_Reviews.tsv", sep='\t',quoting=3)

In [9]:
import nltk, re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
from nltk.corpus import stopwords
review = re.sub('[^a-zA-Z]',' ',data['Review'][0])
review = review.lower().split()
review

['wow', 'loved', 'this', 'place']

In [15]:
preview=[]
for word in review:
  if word not in stopwords.words('english'):
    preview.append(word)

In [16]:
preview

['wow', 'loved', 'place']

In [19]:
review = [word for word in review if word not in stopwords.words('english')]
review

['wow', 'loved', 'place']

In [26]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
review = [ps.stem(word) for word in review]
review = ''.join(review)
review

'w o w   l o v e   p l a c e'

In [29]:
corpus=[]
for i in range(len(data)):
  r = re.sub('[^a-zA-Z]',' ',data['Review'][i])
  r = r.lower().split()
  r = [word for word in r if word not in stopwords.words('english')]
  r = [ps.stem(word) for word in r]
  r = ' '.join(r)
  corpus.append(r)

In [32]:
corpus[1]

'crust good'

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
x = cv.fit_transform(corpus).toarray()
print(x.shape)
y = data.iloc[:, 1].values
print(y.shape)
y[:10]

(1000, 1500)
(1000,)


array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [37]:
#naive bayes algo
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)
x_train.shape, x_test.shape

((800, 1500), (200, 1500))

In [39]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [40]:
y_pred = classifier.predict(x_test)
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_test, y_pred)

0.73

In [43]:
y_pred, y_test

(array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
        1, 1]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 1, 0,